# Generated by Django 2.2.11 on 2020-11-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Registry DTime')),
                ('updated_datetime', models.DateTimeField(auto_now=True, verbose_name='Update DTime')),
                ('first_name', models.CharField(default='', max_length=50, verbose_name='First Name')),
                ('surname', models.CharField(default='', max_length=50, verbose_name='Surname')),
                ('date_of_birth', models.DateField(blank=True, default=None, verbose_name='Registry DTime')),
                ('client_phone', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='client phone')),
                ('nhs_id', models.CharField(blank=True, default='', max_length=11, null=True, verbose_name='nhs id')),
                ('screener', models.TextField(default='', max_length=1500, verbose_name='Screener')),
                ('is_dpoint8', models.BooleanField(blank=True, null=True, verbose_name='is Datapint8')),
                ('left_right_breast', models.TextField(default='', max_length=500, verbose_name='left right breast')),
                ('pos_clockR', models.CharField(choices=[('UpOutPir', 'Upper - outer peripheral'), ('UpInPir', 'Upper - inner peripheral'), ('LowInPir', 'Lower - inner peripheral'), ('LowOutPir', 'Lower - outer peripheral'), ('UpOutCntr', 'Upper - outer central'), ('UpInCntr', 'Upper - inner central'), ('LowInCntr', 'Lower - inner central'), ('LowOutCntr', 'Lower - outer central'), ('LowOutCntr', 'Areola'), ('LowOutCntr', 'Nipple'), ('', 'Null')], default='', max_length=45)),
                ('pos_clockL', models.CharField(choices=[('UpOutPir', 'Upper - outer peripheral'), ('UpInPir', 'Upper - inner peripheral'), ('LowInPir', 'Lower - inner peripheral'), ('LowOutPir', 'Lower - outer peripheral'), ('UpOutCntr', 'Upper - outer central'), ('UpInCntr', 'Upper - inner central'), ('LowInCntr', 'Lower - inner central'), ('LowOutCntr', 'Lower - outer central'), ('LowOutCntr', 'Areola'), ('LowOutCntr', 'Nipple'), ('', 'Null')], default='', max_length=45)),
                ('tumor_size', models.CharField(choices=[('pea', 'Pea'), ('peanut', 'Peanut'), ('grape', 'Grape'), ('walnut', 'Walnut'), ('lemon', 'Lemon'), ('egg', 'Egg'), ('peach', 'Peach'), ('grapefruit', 'Grapefruit'), ('', 'Null')], default='', max_length=15)),
                ('found', models.CharField(choices=[('couplDay', 'Couple of days ago'), ('couplWeeks', 'Couple of weeks ago'), ('fevgWeeks', 'Few weeks ago'), ('couplMont', 'Couple of months ago'), ('fevMont', 'Few months ago'), ('Year', 'A year ago'), ('couplYear', 'Couple of years ago'), ('manyYear', 'Many years ago'), ('', 'Null')], default='', max_length=15)),
                ('proggress', models.CharField(choices=[('slowGrow', 'slowing growing'), ('slowGrow', 'rapidly growing'), ('remainSize', 'remained same in size'), ('decrSize', 'decreased in size'), ('', 'Null')], default='', max_length=15)),
                ('is_datapoint_15', models.BooleanField(blank=True, null=True, verbose_name='is Datapint15')),
                ('is_datapoint_16', models.BooleanField(blank=True, null=True, verbose_name='is Datapint16')),
                ('datapoint_16_a', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4 or more'), ('0', 'Null')], default='', max_length=15)),
                ('datapoint_16_b', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4 or more'), ('0', 'Null')], default='', max_length=15)),
                ('complication', models.CharField(choices=[('S', 'Soft'), ('F', 'Firm'), ('H', 'Hard'), ('N', 'Dont know'), ('', 'Dont know')], default='', max_length=15)),
                ('is_datapoint_18', models.BooleanField(blank=True, null=True, verbose_name='is Datapint18')),
                ('is_datapoint_19', models.BooleanField(blank=True, null=True, verbose_name='is Datapint19')),
                ('is_datapoint_20', models.BooleanField(blank=True, null=True, verbose_name='is Datapint20')),
                ('Datapoint_21', models.CharField(choices=[('1m', 'less than one month'), ('2-3m', '2 - 3 months'), ('3-6m', '3-6 months'), ('6-12m', '6-12 months'), ('1y', 'more than 1 year'), ('', '')], default='', max_length=15)),
                ('Datapoint_22', models.CharField(choices=[('<5%', '<5% of weight'), ('>5%', '>5% of weight'), ('', '')], default='', max_length=15)),
                ('is_datapoint_23', models.BooleanField(blank=True, null=True, verbose_name='is Datapint23')),
                ('is_datapoint_26', models.BooleanField(blank=True, null=True, verbose_name='is Datapint26')),
                ('armpit_pos', models.TextField(default='', max_length=500, verbose_name='armpit pos')),
                ('neck_groin_pos', models.TextField(default='', max_length=500, verbose_name='neck groin pos')),
                ('Datapoint_29', models.TextField(default='', max_length=3500, verbose_name='Datapoint 29')),
                ('Datapoint_30', models.TextField(default='', max_length=3500, verbose_name='Datapoint 30')),
            ],
        ),
    ]
