# Generated by Django 2.2.11 on 2020-11-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbssys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertable',
            name='armpit_pos',
            field=models.TextField(default='', max_length=2000, verbose_name='armpit pos'),
        ),
    ]
