# Generated by Django 2.2.11 on 2020-11-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbssys', '0002_auto_20201108_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertable',
            name='neck_groin_pos',
            field=models.TextField(default='', max_length=2000, verbose_name='neck groin pos'),
        ),
    ]
