# Generated by Django 2.2.11 on 2020-11-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbssys', '0003_auto_20201108_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertable',
            name='nhs_id',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='nhs id'),
        ),
    ]
