# Generated by Django 2.2.11 on 2020-11-08 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jbssys', '0004_auto_20201108_0605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pacient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='phone')),
                ('default_city', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='city')),
                ('home_addres', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='home')),
                ('nsh_id', models.CharField(max_length=9, verbose_name='nsh id')),
            ],
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, verbose_name='Date of birth'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='client', max_length=30, verbose_name='role')),
                ('phone', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='phone')),
                ('default_city', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='city')),
                ('home_addres', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='home')),
                ('work_addres', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='work')),
                ('telegram', models.CharField(blank=True, default='', max_length=60, null=True, verbose_name='telegram')),
                ('user_avatar', models.ImageField(default='mobile/img/sample/avatar/341-3415688_no-avatar-png-transparent-png_yfts1p_xfsloz', upload_to='mobile/img/sample/avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
