# Generated by Django 2.2.11 on 2020-11-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbssys', '0005_auto_20201108_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='nsh_id',
            field=models.CharField(blank=True, default='', max_length=9, null=True, verbose_name='nsh id'),
        ),
    ]
