# Generated by Django 2.2.11 on 2020-11-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbssys', '0006_auto_20201108_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='date_of_birth',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Date of birth'),
        ),
    ]
