# Generated by Django 2.2.11 on 2020-11-08 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jbssys', '0007_pacient_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastertable',
            name='client_phone',
        ),
        migrations.RemoveField(
            model_name='mastertable',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='mastertable',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='mastertable',
            name='nhs_id',
        ),
        migrations.RemoveField(
            model_name='mastertable',
            name='surname',
        ),
        migrations.AddField(
            model_name='mastertable',
            name='pacient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='Pacientmaster', to='jbssys.Pacient'),
            preserve_default=False,
        ),
    ]
