# Generated by Django 2.2.11 on 2020-11-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbssys', '0008_auto_20201108_2331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mastertable',
            name='left_right_breast',
        ),
        migrations.AddField(
            model_name='mastertable',
            name='left_right',
            field=models.CharField(choices=[('RL', 'Right & left'), ('R', 'Right'), ('L', 'Left'), ('', 'Null')], default='', max_length=15),
        ),
    ]
