# Generated by Django 2.2.11 on 2020-11-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbssys', '0009_auto_20201108_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mastertable',
            old_name='Datapoint_29',
            new_name='datapoint_29',
        ),
        migrations.RemoveField(
            model_name='mastertable',
            name='Datapoint_30',
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_100',
            field=models.CharField(choices=[('UpOutPir', 'Upper - outer peripheral'), ('UpInPir', 'Upper - inner peripheral'), ('LowInPir', 'Lower - inner peripheral'), ('LowOutPir', 'Lower - outer peripheral'), ('UpOutCntr', 'Upper - outer central'), ('UpInCntr', 'Upper - inner central'), ('LowInCntr', 'Lower - inner central'), ('LowOutCntr', 'Lower - outer central'), ('LowOutCntr', 'Areola'), ('LowOutCntr', 'Nipple'), ('', 'Null')], default='', max_length=45),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_101',
            field=models.CharField(choices=[('UpOutPir', 'Upper - outer peripheral'), ('UpInPir', 'Upper - inner peripheral'), ('LowInPir', 'Lower - inner peripheral'), ('LowOutPir', 'Lower - outer peripheral'), ('UpOutCntr', 'Upper - outer central'), ('UpInCntr', 'Upper - inner central'), ('LowInCntr', 'Lower - inner central'), ('LowOutCntr', 'Lower - outer central'), ('LowOutCntr', 'Areola'), ('LowOutCntr', 'Nipple'), ('', 'Null')], default='', max_length=45),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_102',
            field=models.CharField(choices=[('couplDay', 'Couple of days ago'), ('couplWeeks', 'Couple of weeks ago'), ('fevgWeeks', 'Few weeks ago'), ('couplMont', 'Couple of months ago'), ('fevMont', 'Few months ago'), ('Year', 'A year ago'), ('couplYear', 'Couple of years ago'), ('manyYear', 'Many years ago'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_103',
            field=models.TextField(default='', max_length=2000, verbose_name='Datapint103'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_104',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint104'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_105',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint105'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_106',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint106'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_107',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint107'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_108',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint108'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_109',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint109'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_110',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint110'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_111',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint111'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_112',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint112'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_113',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint113'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_114',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint114'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_115',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint115'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_116',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint116'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_117',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint117'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_118',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint118'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_119',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint119'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_24',
            field=models.TextField(default='', max_length=2000, verbose_name='Datapoint 24'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_25',
            field=models.TextField(default='', max_length=2000, verbose_name='Datapoint 25'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_30',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint30'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_31',
            field=models.CharField(choices=[('pea', 'Pea'), ('peanut', 'Peanut'), ('grape', 'Grape'), ('walnut', 'Walnut'), ('lemon', 'Lemon'), ('egg', 'Egg'), ('peach', 'Peach'), ('grapefruit', 'Grapefruit'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_32',
            field=models.CharField(choices=[('S', 'Soft'), ('F', 'Firm'), ('H', 'Hard'), ('N', 'Dont know'), ('', 'Dont know')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_33',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('', '')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_34',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('', '')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_35',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('', '')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_36',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('', '')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_37',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('', '')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_38',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('', '')], default='', max_length=3),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_39',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint39'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_40',
            field=models.CharField(choices=[('couplDay', 'Couple of days ago'), ('couplWeeks', 'Couple of weeks ago'), ('fevgWeeks', 'Few weeks ago'), ('couplMont', 'Couple of months ago'), ('fevMont', 'Few months ago'), ('Year', 'A year ago'), ('couplYear', 'Couple of years ago'), ('manyYear', 'Many years ago'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_41',
            field=models.CharField(choices=[('slowGrow', 'slowing growing'), ('slowGrow', 'rapidly growing'), ('remainSize', 'remained same in size'), ('decrSize', 'decreased in size'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_42',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint42'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_43',
            field=models.TextField(default='', max_length=2000, verbose_name='Datapint43'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_44',
            field=models.TextField(default='', max_length=2000, verbose_name='Datapint44'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_45',
            field=models.TextField(default='', max_length=2000, verbose_name='Datapint45'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_46',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint46'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_47',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint47'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_48',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint48'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_49',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint49'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_50',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint50'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_51',
            field=models.CharField(choices=[('couplDay', 'Couple of days ago'), ('couplWeeks', 'Couple of weeks ago'), ('fevgWeeks', 'Few weeks ago'), ('couplMont', 'Couple of months ago'), ('fevMont', 'Few months ago'), ('Year', 'A year ago'), ('couplYear', 'Couple of years ago'), ('manyYear', 'Many years ago'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_52',
            field=models.CharField(choices=[('green', 'Green'), ('watery', 'Watery'), ('white', 'White'), ('bloodstained', 'Blood Stained'), ('brownish', 'Brownish'), ('serous', 'Serous'), ('pus', 'Pus'), ('yellow', 'Yellow'), ('', '')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_53',
            field=models.CharField(choices=[('RL', 'Right & left'), ('R', 'Right'), ('L', 'Left'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_54',
            field=models.CharField(choices=[('onespot', 'One spot'), ('manyspots', 'Many spots'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_55',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint55'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_56',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint56'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_57',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint57'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_58',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint58'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_59',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint59'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_60',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint60'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_61',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint61'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_62',
            field=models.TextField(default='', max_length=2000, verbose_name='Datapint62'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_63',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint63'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_64',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint64'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_65',
            field=models.CharField(choices=[('RL', 'Right & left'), ('R', 'Right'), ('L', 'Left'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_66',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint66'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_67',
            field=models.CharField(choices=[('1', 'Less than a quarter'), ('2', 'More than a quarter but less than half'), ('3', 'More than half of breast'), ('4', 'Whole breast'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_68',
            field=models.CharField(choices=[('couplDay', 'Couple of days ago'), ('couplWeeks', 'Couple of weeks ago'), ('fevgWeeks', 'Few weeks ago'), ('couplMont', 'Couple of months ago'), ('fevMont', 'Few months ago'), ('Year', 'A year ago'), ('couplYear', 'Couple of years ago'), ('manyYear', 'Many years ago'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_69',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint69'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_70',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint70'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_71',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint71'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_72',
            field=models.CharField(choices=[('RL', 'Right & left'), ('R', 'Right'), ('L', 'Left'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_73',
            field=models.CharField(choices=[('couplDay', 'Couple of days ago'), ('couplWeeks', 'Couple of weeks ago'), ('fevgWeeks', 'Few weeks ago'), ('couplMont', 'Couple of months ago'), ('fevMont', 'Few months ago'), ('Year', 'A year ago'), ('couplYear', 'Couple of years ago'), ('manyYear', 'Many years ago'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_74',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint74'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_75',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint75'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_76',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint76'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_77',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint77'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_78',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint78'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_79',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint79'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_80',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint80'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_81',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint81'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_82',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint82'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_83',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint83'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_84',
            field=models.CharField(choices=[('RL', 'Right & left'), ('R', 'Right'), ('L', 'Left'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_85',
            field=models.CharField(choices=[('couplDay', 'Couple of days ago'), ('couplWeeks', 'Couple of weeks ago'), ('fevgWeeks', 'Few weeks ago'), ('couplMont', 'Couple of months ago'), ('fevMont', 'Few months ago'), ('Year', 'A year ago'), ('couplYear', 'Couple of years ago'), ('manyYear', 'Many years ago'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_86',
            field=models.CharField(choices=[('1', 'Rapidly progressing'), ('2', 'Slowly progressing'), ('3', 'No change'), ('4', 'Getting better'), ('', '')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_87',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint87'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_88',
            field=models.TextField(default='', max_length=2000, verbose_name='Datapint88'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_89',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint89'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_90',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint90'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_91',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint91'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_92',
            field=models.CharField(choices=[('couplDay', 'Couple of days ago'), ('couplWeeks', 'Couple of weeks ago'), ('fevgWeeks', 'Few weeks ago'), ('couplMont', 'Couple of months ago'), ('fevMont', 'Few months ago'), ('Year', 'A year ago'), ('couplYear', 'Couple of years ago'), ('manyYear', 'Many years ago'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_93',
            field=models.CharField(choices=[('1', 'Rapidly progressing'), ('2', 'Slowly progressing'), ('3', 'No change'), ('4', 'Getting better'), ('', '')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_94',
            field=models.CharField(choices=[('RL', 'Right & left'), ('R', 'Right'), ('L', 'Left'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_95',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint95'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_96',
            field=models.TextField(default='', max_length=2000, verbose_name='Datapint96'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_97',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint97'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_98',
            field=models.BooleanField(blank=True, null=True, verbose_name='is Datapint98'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='datapoint_99',
            field=models.CharField(choices=[('RL', 'Right & left'), ('R', 'Right'), ('L', 'Left'), ('', 'Null')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='mastertable',
            name='armpit_pos',
            field=models.CharField(choices=[('RLarpit', 'Right & left armpit'), ('Rarpit', 'Right armpit'), ('Larpit', 'Left armpit'), ('', '')], default='', max_length=35),
        ),
    ]
