# Generated by Django 2.2.11 on 2020-11-11 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbssys', '0010_auto_20201109_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(default='doctor', max_length=30, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_avatar',
            field=models.ImageField(default='static/image/avatars/doctor_icon.png', upload_to='static/image/avatars/'),
        ),
    ]
