# Generated by Django 2.2.11 on 2020-12-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbssys', '0014_auto_20201204_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataformtable',
            name='u_score_b',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='u score'),
        ),
    ]
