# Generated by Django 2.2.11 on 2020-12-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbssys', '0015_auto_20201204_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadictionary',
            name='u_score',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='u score'),
        ),
        migrations.AlterField(
            model_name='dataformtable',
            name='u_score',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='u score'),
        ),
        migrations.AlterField(
            model_name='profileformtable',
            name='u_score_p',
            field=models.CharField(blank=True, default='', max_length=9, verbose_name='u score'),
        ),
    ]
