# Generated by Django 2.2.11 on 2020-12-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jbssys', '0016_auto_20201204_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datadictionary',
            name='f_score',
            field=models.CharField(default='0.0', max_length=9, verbose_name='F Score'),
        ),
        migrations.AlterField(
            model_name='datadictionary',
            name='f_score_a',
            field=models.CharField(default='0.0', max_length=9, verbose_name='F Score a'),
        ),
        migrations.AlterField(
            model_name='datadictionary',
            name='f_score_b',
            field=models.CharField(default='0.0', max_length=9, verbose_name='F Score b'),
        ),
    ]
